version: '3.8'

services:
  db:
    image: postgres:15
    container_name: seed_db_container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: seed_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: seed_api_container
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://admin:admin123@db:5432/seed_db
      SECRET_KEY: SementeSegura_998877_Raiz_2026
    depends_on:
      - db
    volumes:
      - ./storage:/app/storage
      - ./models:/app/models

  seed_frontend:
    build: ./frontend
    container_name: seed_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api

volumes:
  postgres_data: